name: Cucumber
description: Cucumber. Simple, Human Collaboration
author: Cucumber Limited
copyright: Cucumber Limited
edit_url: https://github.com/cucumber/website/edit/master/apps/dynamic/views

show_ribbon: false

# Blog
authors:
  aslak:
    display_name: Aslak Hellesøy
    email: aslak@cucumber.pro
    gravatar: 0be0e4aa42aacd9a8a95c792de273ca7
  matt:
    display_name: Matt Wynne
    email: matt@cucumber.pro
    gravatar: cdf378de2284d8acf137122e541caa28
  julien:
    display_name: Julien Biezemans
    email: julien@cucumber.pro
    gravatar: 07193608fb3c70b2a9449d6cafd6d31a
  paul:
    display_name: Paul Rayner
    email: paul@virtual-genius.com
    gravatar: 4ce180eb1538932a4cc5b14c9eb0e83b

versions:
  cucumber_jvm: 1.2.2
